kafka:
  bootstrap:
    servers: united-hare-11568-us1-kafka.upstash.io:9092
  security:
    protocol: SASL_SSL

  sasl:
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username=dW5pdGVkLWhhcmUtMTE1NjgkjDX5tbin9L5jfEIarvEuVBNYAqm3sWZEwd5a1fQ password=YmRkNTk0NTEtNTAyYi00NDhlLWFkNTYtYWMxMGMzZjdhYWFl;

    mechanism: SCRAM-SHA-256

  topic:
    wikimedia: wikimedia-changes

wikimedia:
  event:
    change:
      url: https://stream.wikimedia.org/v2/stream/recentchange


logging:
  config: classpath:logback-spring.xml